import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { getCustomers } from "../services/crm";
import { StatusBadge } from "../components/StatusBadge";
import type { CustomerPage } from "../types";
import { useAuth } from "../store/auth";

const PAGE_SIZE = 20;
export function CustomersPage() {
  const { user } = useAuth(); const [data, setData] = useState<CustomerPage | null>(null); const [query, setQuery] = useState(""); const [activeQuery, setActiveQuery] = useState(""); const [offset, setOffset] = useState(0); const [error, setError] = useState("");
  useEffect(() => { getCustomers({ limit: PAGE_SIZE, offset, q: activeQuery || undefined }).then(setData).catch(() => setError("无法加载客户列表。")); }, [offset, activeQuery]);
  const search = (event: FormEvent) => { event.preventDefault(); setOffset(0); setActiveQuery(query); };
  return <><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-500">客户管理</p><h2 className="text-3xl font-bold">客户</h2></div>{user?.role !== "Viewer" && <Link to="/customers/new" className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white hover:bg-blue-700">新增客户</Link>}</div><form onSubmit={search} className="mt-6 flex max-w-xl gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索公司、联系人、国家或邮箱" className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2" /><button className="rounded-lg border border-slate-300 px-4 py-2 font-medium hover:bg-white">搜索</button></form>{error && <p className="mt-4 text-sm text-rose-600">{error}</p>}<div className="mt-6 overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">公司</th><th className="px-4 py-3">联系人</th><th className="px-4 py-3">国家</th><th className="px-4 py-3">等级</th><th className="px-4 py-3">状态</th></tr></thead><tbody>{data?.items.map((customer) => <tr key={customer.id} className="border-t border-slate-100"><td className="px-4 py-3 font-medium text-blue-700"><Link to={`/customers/${customer.id}`}>{customer.company_name}</Link></td><td className="px-4 py-3">{customer.contact_name ?? "—"}</td><td className="px-4 py-3">{customer.country ?? "—"}</td><td className="px-4 py-3">{customer.level}</td><td className="px-4 py-3"><StatusBadge status={customer.status} /></td></tr>)}{data?.items.length === 0 && <tr><td colSpan={5} className="px-4 py-10 text-center text-slate-500">没有匹配的客户。</td></tr>}</tbody></table></div><div className="mt-4 flex items-center justify-between text-sm"><span className="text-slate-500">共 {data?.total ?? 0} 位客户</span><div className="flex gap-2"><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))} className="rounded border px-3 py-1 disabled:opacity-40">上一页</button><button disabled={!data || offset + PAGE_SIZE >= data.total} onClick={() => setOffset(offset + PAGE_SIZE)} className="rounded border px-3 py-1 disabled:opacity-40">下一页</button></div></div></>;
}
