import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { getCustomers, getTags, type CustomerFilters } from "../services/crm";
import { StatusBadge } from "../components/StatusBadge";
import type { CustomerPage, Tag } from "../types";
import { useAuth } from "../store/auth";

const PAGE_SIZE = 20; const statuses = ["", "Lead", "Contacted", "Quotation", "Negotiation", "Won", "Lost"];
const statusText: Record<string, string> = { "": "全部状态", Lead: "新线索", Contacted: "已联系", Quotation: "报价中", Negotiation: "谈判中", Won: "已成交", Lost: "已流失" };
export function CustomersPage() {
  const { user } = useAuth(); const [data, setData] = useState<CustomerPage | null>(null); const [tags, setTags] = useState<Tag[]>([]); const [filters, setFilters] = useState({ q: "", status: "", level: "", country: "", source: "", tag_id: "" }); const [active, setActive] = useState(filters); const [offset, setOffset] = useState(0); const [error, setError] = useState("");
  useEffect(() => { getTags().then(setTags).catch(() => undefined); }, []);
  useEffect(() => { const params: CustomerFilters = { limit: PAGE_SIZE, offset, ...active, tag_id: active.tag_id ? Number(active.tag_id) : undefined }; getCustomers(params).then(setData).catch(() => setError("无法加载客户列表。")); }, [offset, active]);
  const search = (event: FormEvent) => { event.preventDefault(); setOffset(0); setActive(filters); };
  return <><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-500">外贸客户管理</p><h2 className="text-3xl font-bold">客户</h2></div>{user?.role !== "Viewer" && <Link to="/customers/new" className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">新增客户</Link>}</div>
    <form onSubmit={search} className="mt-6 rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><input value={filters.q} onChange={e => setFilters({ ...filters, q: e.target.value })} placeholder="公司、联系人、国家或邮箱" className="rounded-lg border px-3 py-2" /><select value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value })} className="rounded-lg border px-3 py-2">{statuses.map(s => <option key={s} value={s}>{statusText[s]}</option>)}</select><select value={filters.level} onChange={e => setFilters({ ...filters, level: e.target.value })} className="rounded-lg border px-3 py-2"><option value="">全部等级</option><option>A</option><option>B</option><option>C</option></select><input value={filters.country} onChange={e => setFilters({ ...filters, country: e.target.value })} placeholder="国家/地区" className="rounded-lg border px-3 py-2" /><input value={filters.source} onChange={e => setFilters({ ...filters, source: e.target.value })} placeholder="来源（Alibaba、展会等）" className="rounded-lg border px-3 py-2" /><select value={filters.tag_id} onChange={e => setFilters({ ...filters, tag_id: e.target.value })} className="rounded-lg border px-3 py-2"><option value="">全部标签</option>{tags.map(tag => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select></div><div className="mt-3 flex gap-2"><button className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">搜索</button><button type="button" onClick={() => { const blank = { q: "", status: "", level: "", country: "", source: "", tag_id: "" }; setFilters(blank); setActive(blank); setOffset(0); }} className="rounded-lg border px-4 py-2 text-sm">重置</button></div></form>
    {error && <p className="mt-4 text-sm text-rose-600">{error}</p>}<div className="mt-6 overflow-x-auto rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">公司</th><th className="px-4 py-3">联系人</th><th className="px-4 py-3">国家</th><th className="px-4 py-3">等级</th><th className="px-4 py-3">阶段</th></tr></thead><tbody>{data?.items.map(customer => <tr key={customer.id} className="border-t"><td className="px-4 py-3 font-medium text-blue-700"><Link to={`/customers/${customer.id}`}>{customer.company_name}</Link></td><td className="px-4 py-3">{customer.contact_name ?? "—"}</td><td className="px-4 py-3">{customer.country ?? "—"}</td><td className="px-4 py-3">{customer.level}</td><td className="px-4 py-3"><StatusBadge status={customer.status} /></td></tr>)}{data?.items.length === 0 && <tr><td colSpan={5} className="px-4 py-10 text-center text-slate-500">没有匹配的客户。</td></tr>}</tbody></table></div><div className="mt-4 flex justify-between text-sm"><span className="text-slate-500">共 {data?.total ?? 0} 位客户</span><div className="flex gap-2"><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))} className="rounded border px-3 py-1 disabled:opacity-40">上一页</button><button disabled={!data || offset + PAGE_SIZE >= data.total} onClick={() => setOffset(offset + PAGE_SIZE)} className="rounded border px-3 py-1 disabled:opacity-40">下一页</button></div></div></>;
}
