import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import axios from "axios";
import { createFollowup, getCustomer } from "../services/crm";
import { StatusBadge } from "../components/StatusBadge";
import { useAuth } from "../store/auth";
import type { CustomerDetail } from "../types";

export function CustomerDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const [customer, setCustomer] = useState<CustomerDetail | null>(null); const [error, setError] = useState(""); const [content, setContent] = useState(""); const [type, setType] = useState("Email"); const [saving, setSaving] = useState(false);
  const load = useCallback(() => { if (id) getCustomer(id).then(setCustomer).catch(() => setError("无法加载客户详情。")); }, [id]);
  useEffect(() => { load(); }, [load]);
  async function addFollowup(event: FormEvent) { event.preventDefault(); if (!customer || !user) return; setSaving(true); try { await createFollowup({ customer_id: customer.id, user_id: user.id, type, content }); setContent(""); load(); } catch (err) { setError(axios.isAxiosError(err) ? err.response?.data?.detail ?? "无法创建跟进记录。" : "无法创建跟进记录。"); } finally { setSaving(false); } }
  if (!customer) return <p className="text-slate-500">{error || "加载中…"}</p>;
  const editable = user?.role !== "Viewer";
  return <><Link to="/customers" className="text-sm text-blue-700">← 返回客户列表</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-slate-500">{customer.country ?? "未填写国家"}</p><h2 className="text-3xl font-bold">{customer.company_name}</h2><p className="mt-1 text-slate-600">{customer.contact_name ?? "未设置主联系人"}</p></div><StatusBadge status={customer.status} /></div><section className="mt-7 grid gap-5 lg:grid-cols-2"><article className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">客户信息</h3><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">等级</dt><dd>{customer.level}</dd></div><div><dt className="text-slate-500">来源</dt><dd>{customer.source ?? "—"}</dd></div><div><dt className="text-slate-500">邮箱</dt><dd>{customer.email ?? "—"}</dd></div><div><dt className="text-slate-500">电话</dt><dd>{customer.phone ?? "—"}</dd></div><div><dt className="text-slate-500">WhatsApp</dt><dd>{customer.whatsapp ?? "—"}</dd></div><div><dt className="text-slate-500">网站</dt><dd>{customer.website ?? "—"}</dd></div></dl></article><article className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">联系人</h3><div className="mt-4 space-y-3">{customer.contacts.length ? customer.contacts.map((contact) => <div key={contact.id} className="rounded-lg bg-slate-50 p-3 text-sm"><p className="font-semibold">{contact.name}</p><p className="text-slate-500">{contact.position ?? "—"} · {contact.email ?? contact.phone ?? "—"}</p></div>) : <p className="text-sm text-slate-500">暂无联系人。</p>}</div></article></section><section className="mt-5 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">跟进记录</h3>{editable && <form onSubmit={addFollowup} className="mt-4 grid gap-3 md:grid-cols-[10rem_1fr_auto]"><select value={type} onChange={(e) => setType(e.target.value)} className="rounded border px-3 py-2"><option>Email</option><option>WhatsApp</option><option>Phone</option><option>Meeting</option></select><input required value={content} onChange={(e) => setContent(e.target.value)} placeholder="记录本次沟通内容" className="rounded border px-3 py-2" /><button disabled={saving} className="rounded bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-60">添加</button></form>}<div className="mt-5 space-y-3">{customer.followups.length ? customer.followups.map((followup) => <article key={followup.id} className="border-l-2 border-blue-500 pl-4"><div className="flex gap-3 text-sm"><strong>{followup.type}</strong><span className="text-slate-500">{new Date(followup.created_at).toLocaleString()}</span></div><p className="mt-1 text-sm">{followup.content}</p></article>) : <p className="text-sm text-slate-500">暂无跟进记录。</p>}</div></section></>;
}
