import { useState, type ChangeEvent, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { createCustomer, type CustomerCreatePayload } from "../services/crm";

export function NewCustomerPage() {
  const navigate = useNavigate(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [form, setForm] = useState<CustomerCreatePayload>({ company_name: "", contact_name: "", country: "", email: "", phone: "", whatsapp: "", website: "", source: "", level: "C", status: "Lead" });
  const field = (key: keyof typeof form) => ({ value: form[key], onChange: (e: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm({ ...form, [key]: e.target.value } as CustomerCreatePayload) });
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const customer = await createCustomer(form); navigate(`/customers/${customer.id}`); } catch (err) { setError(axios.isAxiosError(err) ? err.response?.data?.detail ?? "无法创建客户。" : "无法创建客户。"); } finally { setSaving(false); } }
  return <><h2 className="text-3xl font-bold">新增客户</h2><form onSubmit={submit} className="mt-6 max-w-3xl rounded-xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">公司名称<input required {...field("company_name")} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm font-medium">联系人<input {...field("contact_name")} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm font-medium">国家<input {...field("country")} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm font-medium">邮箱<input type="email" {...field("email")} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm font-medium">电话<input {...field("phone")} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm font-medium">WhatsApp<input {...field("whatsapp")} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm font-medium">网站<input {...field("website")} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm font-medium">来源<input {...field("source")} placeholder="Alibaba / Google" className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm font-medium">等级<select {...field("level")} className="mt-1 w-full rounded border px-3 py-2"><option>A</option><option>B</option><option>C</option></select></label><label className="text-sm font-medium">状态<select {...field("status")} className="mt-1 w-full rounded border px-3 py-2"><option>Lead</option><option>Contacted</option><option>Quotation</option><option>Negotiation</option><option>Won</option><option>Lost</option></select></label></div>{error && <p className="mt-4 text-sm text-rose-600">{error}</p>}<div className="mt-6 flex gap-3"><button disabled={saving} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-60">{saving ? "保存中…" : "创建客户"}</button><button type="button" onClick={() => navigate(-1)} className="rounded-lg border px-4 py-2">取消</button></div></form></>;
}
