import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";

import { createQuotation, getOpportunity, getProducts, replaceOpportunityProducts, updateOpportunity } from "../services/crm";
import { useAuth } from "../store/auth";
import type { OpportunityDetail, OpportunityProduct, OpportunityStage, Product } from "../types";

const stages: OpportunityStage[] = ["Lead", "Qualified", "Proposal", "Negotiation", "Won", "Lost"];
const labels: Record<OpportunityStage, string> = { Lead: "初始商机", Qualified: "已确认", Proposal: "方案/报价", Negotiation: "谈判中", Won: "已成交", Lost: "已丢失" };

export function OpportunityDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { user } = useAuth();
  const [opportunity, setOpportunity] = useState<OpportunityDetail | null>(null); const [catalog, setCatalog] = useState<Product[]>([]); const [productLines, setProductLines] = useState<OpportunityProduct[]>([]); const [selectedProduct, setSelectedProduct] = useState("");
  const [stage, setStage] = useState<OpportunityStage>("Lead"); const [amount, setAmount] = useState(""); const [closeDate, setCloseDate] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const editable = user?.role !== "Viewer";
  const load = useCallback(async () => { if (!id) return; try { const item = await getOpportunity(id); setOpportunity(item); setProductLines(item.products); setStage(item.stage); setAmount(item.amount ?? ""); setCloseDate(item.expected_close_date ?? ""); setError(""); } catch { setError("无法加载商机详情。"); } }, [id]);
  useEffect(() => { void load(); void getProducts({ limit: 100, offset: 0, is_active: true }).then((page) => setCatalog(page.items)).catch(() => undefined); }, [load]);
  async function save(event: FormEvent) { event.preventDefault(); if (!opportunity) return; setSaving(true); try { const item = await updateOpportunity(opportunity.id, { stage, amount: amount || undefined, expected_close_date: closeDate || undefined }); setOpportunity(item); setProductLines(item.products); setError(""); } catch { setError("无法更新商机。"); } finally { setSaving(false); } }
  function addProduct() { const product = catalog.find((item) => item.id === Number(selectedProduct)); if (!product || productLines.some((item) => item.product_id === product.id)) return; setProductLines([...productLines, { product_id: product.id, sku: product.sku, name: product.name, quantity: "1", target_price: product.reference_price, reference_price: product.reference_price, currency_code: product.currency_code, image_url: product.images.find((image) => image.is_primary)?.image_url ?? product.images[0]?.image_url ?? null }]); setSelectedProduct(""); }
  async function saveProducts() { if (!opportunity) return; setSaving(true); try { const item = await replaceOpportunityProducts(opportunity.id, productLines.map((line) => ({ product_id: line.product_id, quantity: line.quantity, target_price: line.target_price ?? undefined }))); setOpportunity(item); setProductLines(item.products); setError(""); } catch { setError("无法保存商机产品。"); } finally { setSaving(false); } }
  async function createQuote() { if (!opportunity) return; setSaving(true); try { const quotation = await createQuotation({ opportunity_id: opportunity.id, currency: opportunity.currency }); navigate(`/quotations/${quotation.id}`); } catch { setError("无法创建报价，请先保存至少一个商机产品。"); setSaving(false); } }
  if (!opportunity) return <p className="text-slate-500">{error || "加载中…"}</p>;
  return <><div className="flex items-center justify-between gap-3"><Link to="/opportunities" className="text-sm text-blue-700">← 返回商机列表</Link>{editable && <button disabled={saving} onClick={() => void createQuote()} className="rounded-lg bg-emerald-600 px-4 py-2 font-semibold text-white disabled:opacity-60">Create Quotation</button>}</div><div className="mt-4"><p className="text-sm text-slate-500">{opportunity.public_id}</p><h2 className="mt-1 text-3xl font-bold">{opportunity.name}</h2><Link to={`/customers/${opportunity.customer_id}`} className="mt-1 inline-block text-blue-700">{opportunity.customer_company}</Link></div>{error && <p className="mt-4 text-sm text-rose-600">{error}</p>}
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">商机资料</h3><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">产品需求</dt><dd>{opportunity.interested_product ?? "—"}</dd></div><div><dt className="text-slate-500">负责人</dt><dd>{opportunity.owner_name ?? "—"}</dd></div><div><dt className="text-slate-500">金额</dt><dd>{opportunity.amount ? `${opportunity.currency} ${opportunity.amount}` : "—"}</dd></div><div><dt className="text-slate-500">预计成交</dt><dd>{opportunity.expected_close_date ?? "—"}</dd></div></dl><p className="mt-5 whitespace-pre-wrap text-sm">{opportunity.inquiry_content ?? "暂无询盘内容。"}</p>{editable && <form onSubmit={save} className="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-3"><select value={stage} onChange={(e) => setStage(e.target.value as OpportunityStage)} className="rounded border px-3 py-2">{stages.map((item) => <option key={item} value={item}>{labels[item]}</option>)}</select><input type="number" min="0" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="金额" className="rounded border px-3 py-2" /><input type="date" value={closeDate} onChange={(e) => setCloseDate(e.target.value)} className="rounded border px-3 py-2" /><button disabled={saving} className="w-fit rounded bg-blue-600 px-4 py-2 font-semibold text-white">保存修改</button></form>}</article><article className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">阶段变化记录</h3><div className="mt-4 space-y-4">{opportunity.stage_history.map((history) => <div key={history.id} className="border-l-2 border-blue-500 pl-4 text-sm"><strong>{history.old_stage ? labels[history.old_stage] : "创建商机"} → {labels[history.new_stage]}</strong><p className="text-slate-500">{new Date(history.created_at).toLocaleString()}</p></div>)}</div></article></section>
    <section className="mt-5 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">商机产品</h3><p className="text-sm text-slate-500">报价将从这里复制产品、数量和目标价</p></div>{editable && <div className="flex gap-2"><select value={selectedProduct} onChange={(e) => setSelectedProduct(e.target.value)} className="rounded border px-3 py-2"><option value="">选择产品</option>{catalog.filter((product) => !productLines.some((line) => line.product_id === product.id)).map((product) => <option key={product.id} value={product.id}>{product.sku} · {product.name}</option>)}</select><button onClick={addProduct} className="rounded border px-3 py-2 text-blue-700">添加</button></div>}</div><div className="mt-4 space-y-3">{productLines.map((line, index) => <div key={line.product_id} className="grid items-center gap-3 rounded-lg bg-slate-50 p-3 md:grid-cols-[1fr_120px_160px_auto]"><div><Link to={`/products/${line.product_id}`} className="font-medium text-blue-700">{line.name}</Link><p className="text-xs text-slate-500">{line.sku} · 参考 {line.currency_code} {line.reference_price ?? "—"}</p></div><input disabled={!editable} type="number" min="0.01" step="0.01" value={line.quantity} onChange={(e) => setProductLines(productLines.map((item, current) => current === index ? { ...item, quantity: e.target.value } : item))} className="rounded border px-2 py-1" /><input disabled={!editable} type="number" min="0" step="0.01" value={line.target_price ?? ""} onChange={(e) => setProductLines(productLines.map((item, current) => current === index ? { ...item, target_price: e.target.value || null } : item))} className="rounded border px-2 py-1" />{editable && <button onClick={() => setProductLines(productLines.filter((_, current) => current !== index))} className="text-rose-600">移除</button>}</div>)}{productLines.length === 0 && <p className="text-sm text-slate-500">暂无商机产品。</p>}</div>{editable && <button onClick={() => void saveProducts()} disabled={saving} className="mt-4 rounded bg-slate-900 px-4 py-2 font-semibold text-white">保存产品明细</button>}</section>
    <section className="mt-5 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">关联跟进记录</h3><p className="mt-1 text-sm text-slate-500">完整记录和编辑入口在客户详情页。</p><div className="mt-3 space-y-3">{opportunity.followups.length ? opportunity.followups.map((followup) => <div key={followup.id} className="rounded bg-slate-50 p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><strong>{followup.type}</strong><span className="text-slate-500">跟进日期：{followup.followup_date}</span>{followup.next_followup_date && <span className="text-slate-500">下次：{followup.next_followup_date}</span>}</div><p className="mt-1 whitespace-pre-wrap">{followup.content}</p>{followup.attachments.length > 0 && <p className="mt-2 text-xs text-slate-500">附件：{followup.attachments.map((attachment) => attachment.file_name).join("、")}</p>}</div>) : <p className="text-sm text-slate-500">暂无记录。</p>}</div></section>
  </>;
}
