import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";

import { getOpportunity, updateOpportunity } from "../services/crm";
import { useAuth } from "../store/auth";
import type { OpportunityDetail, OpportunityStage } from "../types";

const stages: OpportunityStage[] = ["Lead", "Qualified", "Proposal", "Negotiation", "Won", "Lost"];
const labels: Record<OpportunityStage, string> = { Lead: "初始商机", Qualified: "已确认", Proposal: "方案/报价", Negotiation: "谈判中", Won: "已成交", Lost: "已丢失" };

export function OpportunityDetailPage() {
  const { id } = useParams(); const { user } = useAuth();
  const [opportunity, setOpportunity] = useState<OpportunityDetail | null>(null);
  const [stage, setStage] = useState<OpportunityStage>("Lead"); const [amount, setAmount] = useState(""); const [closeDate, setCloseDate] = useState("");
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!id) return; try { const item = await getOpportunity(id); setOpportunity(item); setStage(item.stage); setAmount(item.amount ?? ""); setCloseDate(item.expected_close_date ?? ""); setError(""); } catch { setError("无法加载商机详情。"); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function save(event: FormEvent) { event.preventDefault(); if (!opportunity) return; setSaving(true); try { setOpportunity(await updateOpportunity(opportunity.id, { stage, amount: amount || undefined, expected_close_date: closeDate || undefined })); setError(""); } catch { setError("无法更新商机。"); } finally { setSaving(false); } }
  if (!opportunity) return <p className="text-slate-500">{error || "加载中…"}</p>;
  const editable = user?.role !== "Viewer";
  return <><Link to="/opportunities" className="text-sm text-blue-700">← 返回商机列表</Link><div className="mt-4"><p className="text-sm text-slate-500">{opportunity.public_id}</p><h2 className="mt-1 text-3xl font-bold">{opportunity.name}</h2><Link to={`/customers/${opportunity.customer_id}`} className="mt-1 inline-block text-blue-700">{opportunity.customer_company}</Link></div>{error && <p className="mt-4 text-sm text-rose-600">{error}</p>}
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">商机资料</h3><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">产品需求</dt><dd>{opportunity.interested_product ?? "—"}</dd></div><div><dt className="text-slate-500">负责人</dt><dd>{opportunity.owner_name ?? "—"}</dd></div><div><dt className="text-slate-500">金额</dt><dd>{opportunity.amount ? `${opportunity.currency} ${Number(opportunity.amount).toLocaleString()}` : "—"}</dd></div><div><dt className="text-slate-500">预计成交日期</dt><dd>{opportunity.expected_close_date ?? "—"}</dd></div><div><dt className="text-slate-500">阶段</dt><dd>{labels[opportunity.stage]}</dd></div><div><dt className="text-slate-500">创建时间</dt><dd>{new Date(opportunity.created_at).toLocaleString()}</dd></div></dl><h4 className="mt-6 text-sm font-semibold">询盘/需求内容</h4><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{opportunity.inquiry_content ?? "—"}</p>{editable && <form onSubmit={save} className="mt-6 grid gap-3 border-t pt-5 sm:grid-cols-3"><select value={stage} onChange={(event) => setStage(event.target.value as OpportunityStage)} className="rounded border px-3 py-2">{stages.map((item) => <option key={item} value={item}>{labels[item]}</option>)}</select><input type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="金额" className="rounded border px-3 py-2" /><input type="date" value={closeDate} onChange={(event) => setCloseDate(event.target.value)} className="rounded border px-3 py-2" /><button disabled={saving} className="w-fit rounded bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-60">{saving ? "保存中…" : "保存修改"}</button></form>}</article>
      <article className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">阶段变化记录</h3><div className="mt-4 space-y-4">{opportunity.stage_history.map((history) => <div key={history.id} className="relative border-l-2 border-blue-500 pl-4 text-sm before:absolute before:-left-[5px] before:top-1 before:h-2 before:w-2 before:rounded-full before:bg-blue-600"><strong>{history.old_stage ? labels[history.old_stage] : "创建商机"} → {labels[history.new_stage]}</strong><p className="mt-1 text-slate-500">{new Date(history.created_at).toLocaleString()}</p></div>)}</div></article></section>
    <section className="mt-5 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">关联客户信息</h3><div className="mt-3 grid gap-3 text-sm sm:grid-cols-3"><p><span className="text-slate-500">公司：</span>{opportunity.customer.company_name}</p><p><span className="text-slate-500">联系人：</span>{opportunity.customer.contact_name ?? "—"}</p><p><span className="text-slate-500">邮箱：</span>{opportunity.customer.email ?? "—"}</p></div><h4 className="mt-6 text-sm font-semibold">关联跟进记录</h4><div className="mt-3 space-y-3">{opportunity.followups.length ? opportunity.followups.map((followup) => <div key={followup.id} className="rounded-lg bg-slate-50 p-3 text-sm"><div className="flex flex-wrap gap-2"><strong>{followup.type}</strong><span className="text-slate-500">{new Date(followup.created_at).toLocaleString()}</span></div><p className="mt-1 whitespace-pre-wrap">{followup.content}</p></div>) : <p className="text-sm text-slate-500">暂无关联跟进记录。</p>}</div></section></>;
}
