import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { getApiErrorMessage } from "../services/api";
import { completeWorkbenchTask, createWorkbenchTask, deleteWorkbenchTask, getCustomers, getWorkbench, saveDailyWorkNote, saveWorkbenchMetric } from "../services/crm";
import { useAuth } from "../store/auth";
import type { Customer, TaskPriority, WorkbenchMetric, WorkbenchPeriod, WorkbenchToday } from "../types";

type MetricDefinition = { key: string; label: string; isAmount?: boolean };
type MetricSection = { group: string; title: string; items: MetricDefinition[] };
const sections: MetricSection[] = [
  { group: "customer_development", title: "今日客户开发量", items: [{ key: "facebook", label: "Facebook" }, { key: "instagram", label: "Instagram" }, { key: "linkedin", label: "LinkedIn" }, { key: "whatsapp", label: "WhatsApp" }, { key: "email", label: "Email" }, { key: "alibaba", label: "Alibaba" }] },
  { group: "business_work", title: "今日业务工作量", items: [{ key: "inquiry_replies", label: "回复询盘" }, { key: "customer_followups", label: "跟进老客户" }, { key: "quotations", label: "制作报价" }, { key: "sample_handling", label: "样品处理" }, { key: "order_followups", label: "订单跟进" }, { key: "logistics", label: "物流/货代" }, { key: "after_sales", label: "售后" }] },
  { group: "results", title: "今日成果", items: [{ key: "qualified_customers", label: "新增有效客户" }, { key: "customer_replies", label: "客户回复" }, { key: "opportunities", label: "新增商机" }, { key: "quotes_sent", label: "发送报价" }, { key: "orders_won", label: "成交订单" }, { key: "order_amount", label: "成交金额", isAmount: true }] },
];
const priorityLabels: Record<TaskPriority, string> = { high: "高", medium: "中", low: "低" };
const priorityStyles: Record<TaskPriority, string> = { high: "bg-rose-100 text-rose-700", medium: "bg-amber-100 text-amber-700", low: "bg-slate-100 text-slate-700" };
const numberValue = (value: number | string | undefined) => Number(value ?? 0);

export function WorkbenchPage() {
  const { user } = useAuth();
  const [period, setPeriod] = useState<WorkbenchPeriod>("today");
  const [data, setData] = useState<WorkbenchToday | null>(null);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [title, setTitle] = useState(""); const [dueDate, setDueDate] = useState(""); const [priority, setPriority] = useState<TaskPriority>("medium"); const [customerId, setCustomerId] = useState("");
  const [note, setNote] = useState(""); const [busy, setBusy] = useState(false); const [savingNote, setSavingNote] = useState(false); const [error, setError] = useState("");
  const isAdmin = user?.role === "Admin";
  const metricMap = useMemo(() => new Map((data?.metrics ?? []).map((metric) => [`${metric.metric_group}:${metric.metric_key}`, metric])), [data]);

  const load = useCallback(async (nextPeriod: WorkbenchPeriod) => {
    try { const result = await getWorkbench(nextPeriod); setData(result); if (nextPeriod === "today") setNote(result.daily_note?.content ?? ""); setError(""); }
    catch (requestError: unknown) { setError(getApiErrorMessage(requestError, "无法加载每日工作台。")); }
  }, []);
  useEffect(() => { void load(period); }, [load, period]);
  useEffect(() => { void getCustomers({ limit: 100, offset: 0 }).then((page) => setCustomers(page.items)).catch(() => undefined); }, []);
  function metricFor(group: string, key: string): WorkbenchMetric { return metricMap.get(`${group}:${key}`) ?? { metric_group: group, metric_key: key, completed_value: 0, target_value: 0 }; }
  async function saveMetric(metric: WorkbenchMetric) { setBusy(true); try { await saveWorkbenchMetric(metric); await load("today"); } catch (requestError: unknown) { setError(getApiErrorMessage(requestError, "无法保存工作记录。")); } finally { setBusy(false); } }
  async function changeCompleted(metric: WorkbenchMetric, change: number) { await saveMetric({ ...metric, completed_value: Math.max(0, numberValue(metric.completed_value) + change) }); }
  async function changeTarget(metric: WorkbenchMetric, value: string) { await saveMetric({ ...metric, target_value: Math.max(0, Number(value) || 0) }); }
  async function changeAmount(metric: WorkbenchMetric, value: string) { await saveMetric({ ...metric, completed_value: Math.max(0, Number(value) || 0) }); }
  async function createTask(event: FormEvent) { event.preventDefault(); if (!title.trim() || !dueDate) return; setBusy(true); try { await createWorkbenchTask({ title: title.trim(), due_date: dueDate, priority, customer_id: customerId ? Number(customerId) : undefined }); setTitle(""); setCustomerId(""); await load("today"); } catch (requestError: unknown) { setError(getApiErrorMessage(requestError, "无法新增待办。")); } finally { setBusy(false); } }
  async function completeTask(id: number) { setBusy(true); try { await completeWorkbenchTask(id); await load("today"); } catch (requestError: unknown) { setError(getApiErrorMessage(requestError, "无法完成待办。")); } finally { setBusy(false); } }
  async function removeTask(id: number) { setBusy(true); try { await deleteWorkbenchTask(id); await load("today"); } catch (requestError: unknown) { setError(getApiErrorMessage(requestError, "无法删除待办。")); } finally { setBusy(false); } }
  async function persistNote() { setSavingNote(true); try { await saveDailyWorkNote(note); await load("today"); } catch (requestError: unknown) { setError(getApiErrorMessage(requestError, "无法保存今日工作记录。")); } finally { setSavingNote(false); } }

  if (!isAdmin) return <><div><p className="text-sm text-slate-500">每日工作台</p><h2 className="text-3xl font-bold">每日工作台</h2></div><p className="mt-6 rounded-xl bg-amber-50 p-4 text-amber-800">当前工作台仅对 Admin 开放。</p></>;
  return <>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500">工作记录 · {data?.today ?? "加载中"}（上海时间）</p><h2 className="text-3xl font-bold">每日工作台</h2></div><div className="flex rounded-lg bg-slate-100 p-1">{(["today", "week", "month"] as WorkbenchPeriod[]).map((item) => <button type="button" key={item} onClick={() => setPeriod(item)} className={`rounded-md px-4 py-2 text-sm font-semibold ${period === item ? "bg-white text-blue-700 shadow-sm" : "text-slate-600"}`}>{item === "today" ? "今日" : item === "week" ? "本周" : "本月"}</button>)}</div></div>
    {error && <p className="mt-4 text-sm text-rose-600" role="alert">{error}</p>}
    {sections.map((section) => <section key={section.group} className="mt-6 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-baseline justify-between"><h3 className="font-bold">{section.title}</h3><p className="text-sm text-slate-500">{period === "today" ? "完成 / 今日目标" : "完成 / 目标汇总"}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{section.items.map((definition) => { const metric = metricFor(section.group, definition.key); const completed = numberValue(metric.completed_value); const target = numberValue(metric.target_value); return <div key={`${period}:${definition.key}`} className="rounded-lg bg-slate-50 p-4"><p className="font-medium text-slate-800">{definition.label}</p>{definition.isAmount ? <div className="mt-3 flex items-center gap-2"><span className="text-slate-500">¥</span><input disabled={period !== "today" || busy} type="number" min="0" step="0.01" defaultValue={completed} onBlur={(event) => void changeAmount(metric, event.target.value)} className="w-full rounded border bg-white px-2 py-1.5 text-right font-semibold" /></div> : <><div className="mt-3 flex items-center gap-2"><button type="button" disabled={period !== "today" || busy || completed <= 0} onClick={() => void changeCompleted(metric, -1)} className="rounded border bg-white px-2 py-1 font-bold disabled:opacity-40">−</button><strong className="min-w-8 text-center text-xl">{completed}</strong><button type="button" disabled={period !== "today" || busy} onClick={() => void changeCompleted(metric, 1)} className="rounded bg-blue-700 px-2 py-1 font-bold text-white disabled:opacity-40">+</button><span className="ml-auto text-sm text-slate-500">目标</span><input disabled={period !== "today" || busy} type="number" min="0" step="1" defaultValue={target} onBlur={(event) => void changeTarget(metric, event.target.value)} className="w-16 rounded border bg-white px-2 py-1 text-center" /></div><p className="mt-2 text-xs text-slate-500">完成 {completed} / 目标 {target}</p></>}</div>; })}</div></section>)}
    {period === "today" && <><section className="mt-6 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><div><h3 className="font-bold">今日待办</h3><p className="mt-1 text-sm text-slate-500">显示今天到期及已逾期任务。</p></div><span className="text-sm text-slate-500">{data?.tasks.length ?? 0} 项</span></div><form onSubmit={(event) => void createTask(event)} className="mt-5 grid gap-3 rounded-lg bg-slate-50 p-3 md:grid-cols-2"><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="待办标题" className="rounded border px-3 py-2" /><input required type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} className="rounded border px-3 py-2" /><select value={priority} onChange={(event) => setPriority(event.target.value as TaskPriority)} className="rounded border px-3 py-2"><option value="high">高优先级</option><option value="medium">中优先级</option><option value="low">低优先级</option></select><select value={customerId} onChange={(event) => setCustomerId(event.target.value)} className="rounded border px-3 py-2"><option value="">不关联客户</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.company_name}</option>)}</select><button disabled={busy} className="w-fit rounded bg-blue-700 px-4 py-2 font-semibold text-white disabled:opacity-60">新增待办</button></form><div className="mt-4 divide-y">{data?.tasks.map((task) => <div key={task.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{task.title}</p><p className="mt-1 text-sm text-slate-500">截止：{task.due_date}{task.customer_name ? ` · ${task.customer_name}` : ""}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${priorityStyles[task.priority]}`}>{priorityLabels[task.priority]}</span><button type="button" disabled={busy} onClick={() => void completeTask(task.id)} className="text-sm font-semibold text-emerald-700">完成</button><button type="button" disabled={busy} onClick={() => void removeTask(task.id)} className="text-sm text-rose-600">删除</button></div></div>)}{data && !data.tasks.length && <p className="py-6 text-center text-sm text-slate-500">今天没有待办任务。</p>}</div></section><section className="mt-6 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 className="font-bold">今日工作记录</h3><p className="mt-1 text-sm text-slate-500">保存当天重要工作，不会覆盖其他日期的记录。</p><textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={10000} className="mt-4 min-h-40 w-full rounded-lg border p-3" placeholder="例如：与工厂确认样品进度…" /><button type="button" disabled={savingNote} onClick={() => void persistNote()} className="mt-3 rounded bg-slate-900 px-4 py-2 font-semibold text-white disabled:opacity-60">{savingNote ? "保存中…" : "保存工作记录"}</button></section></>}
  </>;
}
